
# copy to config.yaml

# URL of the mantis system, e.g. https://tickets.company.tld
MANTIS_URL:
# user token as created within mantis
MANTIS_TOKEN:

# github personal access token
GITHUB_TOKEN:
# target repo where issues will be created, e.g. user/reponame
GITHUB_REPOSITORY: