name: Pint

on:
    pull_request:

jobs:
    pint:
        name: Pint (PHP-CS-Fixer)
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Install PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: 8.2
                  coverage: none
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            - name: Composer install
              run: composer install --no-interaction --no-ansi --no-progress
            - name: Run Pint
              run: composer run pint
